name: 🐛 Déclarer un bug
description: Rapporter un bug
title: "[BUG]: "
labels: ["bug"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Merci de prendre le temps de remplir ce rapport de bug 🤗
        Assurez-vous qu'il n'y a pas déjà une issue ouverte/clôturée sur ce sujet 😃
        
  - type: dropdown
    id: environment
    attributes:
      label: Où cela est-il arrivé ? En Production, Recette ou Développement ?
      options:
        - Production
        - Recette
        - Développement (Aroban uniquement)
      default: 0    
    validations:
      required: true
      
  - type: input
    id: user
    attributes:
      label: Utilisateur
      description: Indiquez l'identifiant ou l'email relatif à un utilisateur. Utilisez N/A si ce n'est pas relatif un utilisateur connecté.
    validations:
      required: true
      
  - type: textarea
    id: bug-description
    attributes:
      label: Description du bug
      description: Donnez-nous une description courte de ce qui est survenu ET de ce qui aurait dû se passer
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Etapes pour reproduire
      description: Décrivez-nous les étapes pour reproduire le comportement observé.
      placeholder: |
        1. Aller à '...'
        2. Cliquer sur '...'
        3. Scroller vers '...'
        4. Voir l'erreur
    validations:
      required: true
  - type: textarea
    id: additional-information
    attributes:
      label: Informations additionelles
      description: |
        Ajoutez toute information, comme des captures d'écrans, des logs ou toute autre information permettant de faciliter la résolution du problème.
